<a href="https://colab.research.google.com/github/Stephen-G-Peterson/MachineLearning/blob/main/HW1_Stephen_Peterson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
import seaborn as sns # import the seaborn library
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report

In [8]:
iot_data = pd.read_csv("/iot_dataset.csv")
iot_data.head()

      x1      x2      x3    x4    x5      x6    y
0  34.40 -16.400  2600.0  26.7  2.92  1950.0  0.0
1  30.40   1.140  1770.0  30.2  1.91  1030.0  1.0
2  19.90  -4.050  2430.0  29.9  2.25  1670.0  0.0
3  30.70   0.231  2330.0  25.6  2.29  1580.0  1.0
4   3.73  12.600   372.0  48.5  0.28  1040.0  0.0

In [13]:
iot_data = iot_data.rename(columns={'x1': 'temp', 'x2': 'humidity', 'x3': 'light', 'x4': 'noise', 'x5': 'motion', 'x6': 'device ID', 'y': 'class'})
iot_data.head()

    temp  humidity   light  noise  motion  device ID  class
0  34.40   -16.400  2600.0   26.7    2.92     1950.0      0
1  30.40     1.140  1770.0   30.2    1.91     1030.0      1
2  19.90    -4.050  2430.0   29.9    2.25     1670.0      0
3  30.70     0.231  2330.0   25.6    2.29     1580.0      1
4   3.73    12.600   372.0   48.5    0.28     1040.0      0